In [83]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn


In [84]:
dataset = pd.read_csv('employee.csv')
dataset.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                     5   
1               other                1   30                     5   
2            sourcing                1   34                     3   
3               other                2   39                     1   
4               other                1   45                     3   

   length_of_service  awards_won  avg_training_score  is_promoted  
0                  8           0                  49            0  
1                  4           0                  60            0  
2                  7           0                  50            0  
3                 10           0                  50            0  
4                  2           0                  73            0

In [85]:
dataset

employee_id         department     region         education gender  \
0            65438  Sales & Marketing   region_7  Master's & above      f   
1            65141         Operations  region_22        Bachelor's      m   
2             7513  Sales & Marketing  region_19        Bachelor's      m   
3             2542  Sales & Marketing  region_23        Bachelor's      m   
4            48945         Technology  region_26        Bachelor's      m   
...            ...                ...        ...               ...    ...   
54803         3030         Technology  region_14        Bachelor's      m   
54804        74592         Operations  region_27  Master's & above      f   
54805        13918          Analytics   region_1        Bachelor's      m   
54806        13614  Sales & Marketing   region_9        Bachelor's      m   
54807        51526                 HR  region_22        Bachelor's      m   

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                sourcing                1   35                     5   
1                   other                1   30                     5   
2                sourcing                1   34                     3   
3                   other                2   39                     1   
4                   other                1   45                     3   
...                   ...              ...  ...                   ...   
54803            sourcing                1   48                     3   
54804               other                1   37                     2   
54805               other                1   27                     5   
54806            sourcing                1   29                     1   
54807               other                1   27                     1   

       length_of_service  awards_won  avg_training_score  is_promoted  
0                      8           0                  49            0  
1                      4           0                  60            0  
2                      7           0                  50            0  
3                     10           0                  50            0  
4                      2           0                  73            0  
...                  ...         ...                 ...          ...  
54803                 17           0                  78            0  
54804                  6           0                  56            0  
54805                  3           0                  79            0  
54806                  2           0                  79            0  
54807                  5           0                  49            0  

[54808 rows x 13 columns]

In [86]:
kolom_kosong = dataset.columns[dataset.isna().any()].tolist()

data = dataset.dropna(subset=kolom_kosong)


In [87]:
dataset = dataset.drop('employee_id', axis=1)

In [88]:
X = dataset.iloc[:, :11].values
y = dataset.iloc[:, -1].values

In [89]:
print(X)

[['Sales & Marketing' 'region_7' "Master's & above" ... 8 0 49]
 ['Operations' 'region_22' "Bachelor's" ... 4 0 60]
 ['Sales & Marketing' 'region_19' "Bachelor's" ... 7 0 50]
 ...
 ['Analytics' 'region_1' "Bachelor's" ... 3 0 79]
 ['Sales & Marketing' 'region_9' "Bachelor's" ... 2 0 79]
 ['HR' 'region_22' "Bachelor's" ... 5 0 49]]


In [90]:
print(y)

[0 0 0 ... 0 0 0]


In [91]:
from sklearn.preprocessing import LabelEncoder

In [92]:
le = LabelEncoder()
X[:,0]= le.fit_transform(X[:,0])

In [93]:
print(X)

[[7 'region_7' "Master's & above" ... 8 0 49]
 [4 'region_22' "Bachelor's" ... 4 0 60]
 [7 'region_19' "Bachelor's" ... 7 0 50]
 ...
 [0 'region_1' "Bachelor's" ... 3 0 79]
 [7 'region_9' "Bachelor's" ... 2 0 79]
 [2 'region_22' "Bachelor's" ... 5 0 49]]


In [94]:
le = LabelEncoder()
X[:,1]= le.fit_transform(X[:,1])

In [95]:
le = LabelEncoder()
X[:,2]= le.fit_transform(X[:,2])

In [96]:
le = LabelEncoder()
X[:,3]= le.fit_transform(X[:,3])

In [97]:
le = LabelEncoder()
X[:,4]= le.fit_transform(X[:,4])

In [98]:
le = LabelEncoder()
X[:,5]= le.fit_transform(X[:,5])

In [99]:
print(X)

[[7 31 2 ... 8 0 49]
 [4 14 0 ... 4 0 60]
 [7 10 0 ... 7 0 50]
 ...
 [0 0 0 ... 3 0 79]
 [7 33 0 ... 2 0 79]
 [2 14 0 ... 5 0 49]]


In [100]:
from sklearn.model_selection import train_test_split

In [101]:
X_train, X_test, y_train , y_test = train_test_split(X,y, test_size=0.1, random_state=0)

In [102]:
from sklearn.impute import SimpleImputer

# Inisialisasi SimpleImputer dengan strategi 'mean'
imputer = SimpleImputer(strategy='mean')

# Menggunakan imputer untuk mengisi nilai NaN di X_train
X_train = imputer.fit_transform(X_train)


In [103]:
print(X_test)

[[8 31 2 ... 7 0 78]
 [8 14 2 ... 4 0 76]
 [5 23 0 ... 1 0 68]
 ...
 [7 10 0 ... 3 0 52]
 [4 14 0 ... 7 0 60]
 [4 12 0 ... 5 0 60]]


In [104]:
print(y_test)

[0 0 0 ... 0 0 0]


In [105]:
from sklearn.preprocessing import StandardScaler

In [106]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [107]:
print(X_train)

[[-0.38744464  1.43383982 -0.64701833 ... -1.13962369 -0.15332694
  -0.12589953]
 [-0.38744464  0.97753207 -0.64701833 ...  0.97201687 -0.15332694
   0.76036058]
 [ 0.8087924  -1.30400668 -0.64701833 ...  0.97201687 -0.15332694
  -1.08601466]
 ...
 [ 0.8087924  -0.50546812 -0.64701833 ... -0.67037024 -0.15332694
  -1.08601466]
 [ 1.20753808 -0.16323731 -0.64701833 ...  0.03350995 -0.15332694
   1.12963563]
 [ 1.20753808  1.43383982 -0.64701833 ... -0.20111678 -0.15332694
   1.27734565]]


In [108]:
from sklearn.naive_bayes import GaussianNB

In [109]:
from sklearn.naive_bayes import GaussianNB

# Membuat instance GaussianNB
classifier = GaussianNB()

# Melatih model GaussianNB pada data pelatihan
classifier.fit(X_train, y_train)

# Sekarang Anda dapat menggunakannya untuk membuat prediksi
y_pred = classifier.predict(X_test)

In [110]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [111]:
print(y_test)

[0 0 0 ... 0 0 0]


In [112]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [113]:
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

In [114]:
ac

0.913154533844189

In [116]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Inisialisasi LabelEncoder
label_encoder = LabelEncoder()

# Data tes Anda dalam bentuk dictionary
data_testing = {
    "department": ["Sales & Marketing"],
    "region": ["region_4"],
    "education": ["Bachelor's"],
    "gender": ["m"],
    "recruitment_channel": ["sourcing"],
    "no_of_trainings": [1],
    "age": [49],
    "previous_year_rating": [5],
    "length_of_service": [5],
    "awards_won": [0],
    "avg_training_score": [49]
}

# Buat DataFrame dari data tes
X_test = pd.DataFrame(data_testing)

# Loop melalui setiap kolom kategori dalam data tes Anda dan menerapkan transformasi
for col in ["department", "region", "education", "gender", "recruitment_channel"]:
    X_test[col] = label_encoder.fit_transform(X_test[col])

# Gunakan model GaussianNB untuk membuat prediksi
y_pred = classifier.predict(X_test)

# Anda dapat melakukan pengujian hasil prediksi di sini
if y_pred == 0:
    hasil = "tidak naik jabatan"
elif y_pred == 1:
    hasil = "naik jabatan"
else:
    hasil = "error"

print(hasil)


naik jabatan


c:\Users\roikh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


In [118]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Inisialisasi LabelEncoder
label_encoder = LabelEncoder()

# Data tes Anda dalam bentuk dictionary
data_testing = {
    "department": ["Sales & Marketing"],
    "region": ["region_4"],
    "education": ["Bachelor's"],
    "gender": ["m"],
    "recruitment_channel": ["sourcing"],
    "no_of_trainings": [1],
    "age": [60],
    "previous_year_rating": [5],
    "length_of_service": [5],
    "awards_won": [0],
    "avg_training_score": [30]
}

# Buat DataFrame dari data tes
X_test = pd.DataFrame(data_testing)

# Loop melalui setiap kolom kategori dalam data tes Anda dan menerapkan transformasi
for col in ["department", "region", "education", "gender", "recruitment_channel"]:
    X_test[col] = label_encoder.fit_transform(X_test[col])

# Gunakan model GaussianNB untuk membuat prediksi
y_pred = classifier.predict(X_test)

# Anda dapat melakukan pengujian hasil prediksi di sini
if y_pred == 0:
    hasil = "tidak naik jabatan"
elif y_pred == 1:
    hasil = "naik jabatan"
else:
    hasil = "error"

print(hasil)


tidak naik jabatan


c:\Users\roikh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


In [122]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Inisialisasi LabelEncoder
label_encoder = LabelEncoder()

# Data tes Anda dalam bentuk dictionary
data_testing = {
    "department": ["Analytics"],
    "region": ["region_22"],
    "education": ["Bachelor's"],
    "gender": ["f"],
    "recruitment_channel": ["referred"],
    "no_of_trainings": [2],
    "age": [29],
    "previous_year_rating": [1],
    "length_of_service": [3],
    "awards_won": [0],
    "avg_training_score": [50]
}

# Buat DataFrame dari data tes
X_test = pd.DataFrame(data_testing)

# Loop melalui setiap kolom kategori dalam data tes Anda dan menerapkan transformasi
for col in ["department", "region", "education", "gender", "recruitment_channel"]:
    X_test[col] = label_encoder.fit_transform(X_test[col])

# Gunakan model GaussianNB untuk membuat prediksi
y_pred = classifier.predict(X_test)

# Anda dapat melakukan pengujian hasil prediksi di sini
if y_pred == 0:
    hasil = "tidak naik jabatan"
elif y_pred == 1:
    hasil = "naik jabatan"
else:
    hasil = "error"

print(hasil)


naik jabatan


c:\Users\roikh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


In [125]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Inisialisasi LabelEncoder
label_encoder = LabelEncoder()

# Data tes Anda dalam bentuk dictionary
data_testing = {
    "department": ["Analytics"],
    "region": ["region_22"],
    "education": ["Bachelor's"],
    "gender": ["f"],
    "recruitment_channel": ["referred"],
    "no_of_trainings": [2],
    "age": [46],
    "previous_year_rating": [1],
    "length_of_service": [3],
    "awards_won": [0],
    "avg_training_score": [35]
}

# Buat DataFrame dari data tes
X_test = pd.DataFrame(data_testing)

# Loop melalui setiap kolom kategori dalam data tes Anda dan menerapkan transformasi
for col in ["department", "region", "education", "gender", "recruitment_channel"]:
    X_test[col] = label_encoder.fit_transform(X_test[col])

# Gunakan model GaussianNB untuk membuat prediksi
y_pred = classifier.predict(X_test)

# Anda dapat melakukan pengujian hasil prediksi di sini
if y_pred == 0:
    hasil = "tidak naik jabatan"
elif y_pred == 1:
    hasil = "naik jabatan"
else:
    hasil = "error"

print(hasil)


tidak naik jabatan


c:\Users\roikh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


In [119]:
import pickle

In [120]:
filename = 'revisi.sav'
pickle.dump(classifier, open(filename,'wb'))